/*
 * people.C
 *   Generate people for the elevators simulation
 *
 * Bryan Clair
 * 2006
 *
 */
#include <iostream>
#include <sstream>
#include <time.h>
#include <stdlib.h>
using namespace std;

#define MAXFLOOR 10

#define NAMES 24

string fnames[] = {
  "Phil",     "Pat",      "Peyton",  "Chamique",
  "Jamal",    "Tamika",   "Terry",   "Teresa",
  "Peerless", "Semeka",   "Al",      "Kristin",
  "Tori",     "Misty",    "Marcus",  "Kellie",
  "Leonard",  "LaShonda", "Trey",    "Byrnae",
  "Mercedes", "Kyra",     "Jonathan","Niya"
};

string lnames[] = {
  "Fulmer",   "Summitt",  "Manning", "Holdsclaw",
  "Lewis",    "Catchings","Fair",    "Geter",  
  "Price",    "Randall",  "Wilson",  "Clement", 
  "Noel",     "Greene",   "Nash",    "Jolly",
  "Little",   "Stevens",  "Teague",  "Laxton",
  "Hamilton", "Elzy",     "Brown",   "Butts"
};

//
// make_name
//   Create a name string, unique for each integer i
//
string make_name(int i)
{
  if (i < NAMES) return fnames[i];
  else if (i < NAMES*NAMES) 
    return fnames[i % NAMES] + "_" + lnames[(i - 1 + i/NAMES) % NAMES];
  else {
    stringstream s;
    s << "P" << i;
    return s.str();
  }
}

//
// make_person
//   Output a new person record with given name and # of trips
//
void make_person(string name, int trips, int delaymax) {
  cout << name;

  cout << " " << random()%delaymax+1; // start time
  
  int floor = 1;
  for (int i = 0; i < trips; i++) {
    floor = (floor + 1 + random()%MAXFLOOR)%(MAXFLOOR+1);
    cout << " " << floor;
    cout << " " << random()%delaymax+1;
  }
  // return to ground floor to leave
  if (floor != 1) {
    cout << " " << 1;
    cout << " " << 0;
  }
  cout << endl;
}

//
// usage
//   Print a usage error message
//
void usage(char *name, const char *err = NULL)
{
  cerr << "usage: " << name << " [-p people] [-t trips] [-d delaymax]"
       << endl;
  if (err) cerr << "       " << err << endl;
  exit(1);
}

//
// main
//
main(int argc,char *argv[])
{
  // default values for arguments
  int people = 5;
  int trips = 5;
  int delaymax = 15;

  char opt;
  while ((opt = getopt(argc,argv,"p:t:d:")) != -1)
    switch (opt) {
    case 'p':
      people = atoi(optarg);
      break;
    case 't':
      trips = atoi(optarg);
      break;
    case 'd':
      delaymax = atoi(optarg);
      break;
    default:
      usage(argv[0]);
    }

  if (optind != argc) usage(argv[0]);
  if (people < 1) usage(argv[0],"people must be > 0");
  if (trips < 1) usage(argv[0],"trips must be > 0");
  if (delaymax < 1) usage(argv[0],"delaymax must be > 0");

  time_t now=time(NULL);
  srandom(now);

  cout << "# Automatically generated by " << argv[0] << " on " << ctime(&now);
  cout << "# " << people << " people, " << trips << " trips." << endl;

  for (int i=0; i < people; i++) {
    make_person(make_name(i),trips,delaymax);
  }
}
